version: '3.7'

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
  service_clientes:
    image: wesleywillians/kong-service:latest
    environment:
      PORT: ":8081"
      CONTENT: "<h1>Service Clientes</h1>"
    networks:
      - kong-net
    ports:
      - 8081:8081

  service_users:
    image: wesleywillians/kong-service:latest
    environment:
      PORT: ":8082"
      CONTENT: "<h1>Service Users</h1>"
    networks:
      - kong-net
    ports:
      - 8082:8082

  service_extrato:
    image: wesleywillians/kong-service:latest
    environment:
      PORT: ":8083"
      CONTENT: "<h1>Service Extrato</h1>"
    networks:
      - kong-net
    ports:
      - 8083:8083